# Site Settings
title: Resume
url:
baseurl: #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: 문희주
tagline: 안드로이드 개발자
pic: profile.gif  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary:
    안녕하세요. 안드로이드 개발자를 꿈꾸는 문희주입니다.</br></br>
    <h5>[개발자가 되고 싶은 이유]</h5>
    개발자에게 가장 중요한 것은 사용자와의 소통이라고 생각합니다. 아무리 기술적으로 뛰어난 프로그램이더라도 사용자의 만족을 끌어내지 못하면 소용없기 때문입니다. 저는 사용자의 의견을 수용하며 더 나은 프로그램을 만들어 나가는 과정에서 보람을 느낍니다. 또한, 사용자의 만족하는 모습은 개발자로서 자부심을 느끼기 때문에 개발자가 되고 싶습니다.</br></br>
    <h5>[관심 분야]</h5>
    실생활과 밀접한 AI를 활용한 분야, O2O에 관심이 있습니다.
    객체지향 프로그래밍(OOP)과 MVVM, MVP 등 아키텍쳐 설계에 관심이 있고 UI/UX에 관심을 갖고 학습 중입니다.</br></br>
    <h5>[최종 목표]</h5>
    사용자의 불편사항을 근본적으로 고민하며 효율적으로 문제를 해결하는 개발자가 되고 싶습니다.

#sidebar links
email: gheepie@gmail.com
phone: +82 10 - 7273 - 2966
website: heepie.tistory.com #do not add http://
# linkedin: alandoe
github: heepie
# twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
